### ISSUE TITLE
Update Documentation upon Electron Release

### ISSUE THREAD

**Issue by jlord** [electron/electron.atom.io#51]
Currently updating the documentation here when there is a new minor release of Electron is a manual process of running a script in this repository. Having this be built into the process of the release would make it happen more timely :watch: 

@zcbenz how would you prefer to do that? We could have a script in `atom/electron` that runs a another process and checks out `atom/electron.atom.io`, runs `script/docs` and then pushes it to `master` here (or even opens up a Pull Request). Would you be ok having something like that in Electron or you would you prefer it be set up as a web hook and executed elsewhere?

**Comment by zcbenz** [comment]
@jlord I prefer to update the documents via web hooks, but I think neither way would work well for how we update the website now, because writing a script to push commits to repo is hard to get right and from my experience such script always tends to encounter unexpected errors after a long run.

I think we should not put electron's documents into this repo, a possible better way is to download the documents when the website is running, in following workflow:

_When the website is started_

1. Pull the list of Electron's releases.
2. Check what we have in `_docs`.
3. Download missing documents into `_docs` by unzipping each release's source tarball. If it is started for the first time we will download the documents of all releases.
4. Start serving.

_When there is a new release of Electron_

1. The website get notified via web hook.
2. Check if we already have this release in `_docs`, it could happen if I accidentally unpublished a release and then republished it.
3. Download the documents of new release into `_docs`.

The atom.io seems to work in this way, I don't know much about RoR but it might be possible to reuse code there.

**Comment by zeke** [comment]
This is a thing now! We set up a Heroku app that runs every ten minutes.

See the release script here: https://github.com/electron/electron.atom.io/blob/cbe46dd421e91d2eddbee0d46d670d8afface771/script/release
